version: "3"
services:
  web:
    build: ./petshop/
    networks:
      - webnet
  nginx:
    build: ./h5-admin/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
